#### Name : Shivam Baghele
#### Roll No : A3 - 63
#### Subject : Machine Learning
#### Practical 07

XOR prolem solving using BPN.

In [10]:
import numpy as np

# sigmoid activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))
# sigmoid derivative
def sigmoid_derivative(x):
    return x * (1 - x)

# XOR data
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [0]])

#Neural Network architecture
input_size = 2
hidden_size = 4
output_size = 1
learning_rate = 0.1

# Initialize weights and biases
np.random.seed(42)
weights_input_hidden = np.random.uniform(size=(input_size, hidden_size))
bias_hidden = np.zeros((1, hidden_size))
weights_hidden_output = np.random.uniform(size=(hidden_size, output_size))
bias_output = np.zeros((1, output_size))

# Training
epochs = 10000
for epoch in range(epochs):
    # Forward propagation
    hidden_input = np.dot(X, weights_input_hidden) + bias_hidden
    hidden_output = sigmoid(hidden_input)
    output_layer_input = np.dot(hidden_output, weights_hidden_output) + bias_output
    predicted_output = sigmoid(output_layer_input)

    # Calculate the error
    error = y - predicted_output

    # Backpropagation
    d_output = error * sigmoid_derivative(predicted_output)
    error_hidden_layer = d_output.dot(weights_hidden_output.T)
    d_hidden_layer = error_hidden_layer * sigmoid_derivative(hidden_output)

    # Update weights and biases
    weights_hidden_output += hidden_output.T.dot(d_output) * learning_rate
    weights_input_hidden += X.T.dot(d_hidden_layer) * learning_rate
    bias_output += np.sum(d_output, axis=0, keepdims=True) * learning_rate
    bias_hidden += np.sum(d_hidden_layer, axis=0, keepdims=True) * learning_rate

    # Display the error at certain intervals
    if epoch % 1000 == 0:
        mean_error = np.mean(np.abs(error))
        print(f"Epoch {epoch}: Error = {mean_error}")
        print(f"weights_input_hidden =\n{weights_input_hidden}")
        print(f"bias_hidden ={bias_hidden}")
        print(f"weights_hidden_output =\n{weights_hidden_output} ")
        print(f"bias_output={bias_output}")
        print()


# Testing the trained model
test_input = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
predicted_output = sigmoid(np.dot(sigmoid(np.dot(test_input, weights_input_hidden) + bias_hidden), weights_hidden_output) + bias_output)
print("-------------------------------------------------------------------------")
print("Predicted XOR outputs:")
print(predicted_output)



Epoch 0: Error = 0.4965166892314006
weights_input_hidden =
[[0.37339358 0.94964754 0.73195763 0.59763436]
 [0.15495067 0.15509735 0.0580513  0.8651894 ]]
bias_hidden =[[-2.76182569e-03 -2.96946207e-03 -9.15451746e-05 -3.75262487e-03]]
weights_hidden_output =
[[0.59056324]
 [0.69653048]
 [0.00954003]
 [0.95801566]] 
bias_output=[[-0.01900371]]

Epoch 1000: Error = 0.4873148164354445
weights_input_hidden =
[[ 0.31177933  0.94062471  0.81339024  1.41419855]
 [ 0.09488521  0.27950574 -0.00462046  1.4999884 ]]
bias_hidden =[[-0.05507398 -0.00333484  0.01545471  0.20046702]]
weights_hidden_output =
[[ 0.11045767]
 [ 0.1655882 ]
 [-0.56112574]
 [ 1.16889131]] 
bias_output=[[-0.73550354]]

Epoch 2000: Error = 0.4184354737536522
weights_input_hidden =
[[0.36779611 0.96430335 1.13344296 3.11495718]
 [0.19899927 0.31711165 0.14056611 2.97742039]]
bias_hidden =[[-0.05755547 -0.05299421 -0.04552133 -0.39235056]]
weights_hidden_output =
[[-0.34045886]
 [-0.49736264]
 [-1.22905621]
 [ 2.99254633]] 
b