5(a) Implementation of KNN algorithm for regression as per given dataset.


In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [ ]:
import numpy as np
import pandas as pd
import math as mt

In [ ]:
data =pd.read_csv("/content/gdrive/MyDrive/ml_lab/regression.csv")

In [ ]:
data

Length  Weight  Cost
0       10      15    45
1       11       6    37
2       12      14    48
3        7       9    33
4        9      14    38
5        8      12    40
6        6      11    35
7       15      10    50
8       14       8    46
9        7      12    35
10      10       6    36
11      13       8    44
12       9       7    32
13       5       8    30
14       5      10    30

In [ ]:
list= np.array(data)[ : , : -1]
print(list)

[[10 15]
 [11  6]
 [12 14]
 [ 7  9]
 [ 9 14]
 [ 8 12]
 [ 6 11]
 [15 10]
 [14  8]
 [ 7 12]
 [10  6]
 [13  8]
 [ 9  7]
 [ 5  8]
 [ 5 10]]


In [ ]:
cost= np.array(data)[ : , -1]
print(cost)

[45 37 48 33 38 40 35 50 46 35 36 44 32 30 30]


In [ ]:
dist=[]
def findCost(x,y,k):
  dist=[]
  ans=0;
  for i in range(0,len(list)):
    ele=mt.sqrt(pow((list[i][0]-x),2)+pow((list[i][1]-y),2))
    dist.append([ele,cost[i]])
  dist.sort()
  for i in range(0,k):
    ans=ans+dist[i][1]
  ans=ans/k
  return ans

In [ ]:
x=int(input('Enter a length of rod : '))
y= int(input('Enter a weight of rod : '))
k=int(input('Enter a value of K : '))
print("predicted cost of a rod is : ",findCost(x,y,k))

Enter a length of rod : 7
Enter a weight of rod : 8
Enter a value of K : 3
predicted cost of a rod is :  31.666666666666668


---------------------------------------------------------------------------


5(b) Implementation of KNN algorithm for classification using Iris dataset.

In [ ]:
import numpy as nm
import matplotlib.pyplot as mtp
import pandas as pd

In [ ]:
data =pd.read_csv("/content/gdrive/MyDrive/ml_lab/Iris.csv")
print(data.head(7))

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa
6   7            4.6           3.4            1.4           0.3  Iris-setosa


In [ ]:
x= data.iloc[:,[1,2,3,4]].values
y= data.iloc[:, 5].values

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.3, random_state=0)


In [ ]:
from sklearn.preprocessing import StandardScaler
st_x= StandardScaler()
x_train= st_x.fit_transform(x_train)
x_test= st_x.transform(x_test)


In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier= KNeighborsClassifier(n_neighbors=8, metric='minkowski', p=2 )
classifier.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=8)

In [ ]:

y_pred= classifier.predict(x_test)
y_pred

array(['Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-setosa'], dtype=object)

In [ ]:
from sklearn.metrics import confusion_matrix
cm= confusion_matrix(y_test, y_pred)

print(cm)

[[16  0  0]
 [ 0 17  1]
 [ 0  0 11]]


In [ ]:
from sklearn import metrics
Accuracy = metrics.accuracy_score(y_test, y_pred)
print("Accuracy : ",Accuracy)

Accuracy :  0.9777777777777777
